---
title: La música que me gusta
author: Lucas Martino
date: '2026-02-09'
toc: true
slug: la-musica-que-me-gusta
categories: []
tags: []
---

## Presentación

Me he dado cuenta que me gusta escuchar música de bandas o artistas de diferentes
países, así que a continuación, voy a hacer una **lista de la música** que escucho
dividida en cada país con una **breve introducción** de cada banda o artista y al
final una **canción de muestra**.

Esta lista no representa absolutamente todas las bandas o artistas que escucho, sino **los que
más me gustan**

## Argentina

### Soda Stereo

**Soda Stereo** es una banda de rock **formada en 1982**, compuesta por [Gustavo
Cerati](https://es.wikipedia.org/wiki/Gustavo_Cerati), [Zeta
Bosio](https://es.wikipedia.org/wiki/Zeta_Bosio) y [Charly
Alberti](https://es.wikipedia.org/wiki/Charly_Alberti). Protagonizaron géneros
como: pop rock, new wave, rock alternativo y rock electrónico.

<iframe width="658" height="468" src="https://www.youtube.com/embed/vo7jBHB66q4?list=RDvo7jBHB66q4" title="En la Ciudad de la Furia" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Gustavo Cerati

Gustavo Cerati nació el 11 de agosto de 1959. Es conocido por ser líder,
vocalista, compositor y guitarrista de la banda de rock [Soda
Stereo](#soda-stereo). Comenzó su carrera como solista en 1993 con su disco 
[Amor Amarillo](https://es.wikipedia.org/wiki/Amor_amarillo) y se consolidó 
luego de la separación de Soda Stereo en 1997. 

<iframe width="658" height="468" src="https://www.youtube.com/embed/O-sKl38qPQA?list=RDO-sKl38qPQA" title="Gustavo Cerati - Rapto" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Luís Alberto Spinetta

Luís Alberto Spinetta nació el 23 de enero de 1950. Comenzó su carrera formando
distintas bandas de rock en las décadas de los 60 y 70, por ejemplo:
[Almendra](https://es.wikipedia.org/wiki/Almendra_(banda)), [Pescado
Rabioso](https://es.wikipedia.org/wiki/Pescado_Rabioso) e
[Invisible](https://es.wikipedia.org/wiki/Invisible_(banda)), introductoras de
géneros como: hard rock, blues, y rock progresivo.

<iframe width="658" height="468" src="https://www.youtube.com/embed/Wvmfopb2b9A?list=RDWvmfopb2b9A" title="Cielo De Ti" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Gilda

Gilda nació el 11 de octubre de 1961, era originalmente una maestra jardinera
que luego se volcó a la música. Se destacó rápidamente en el género de **cumbia
tropical**.

<iframe width="658" height="468" src="https://www.youtube.com/embed/wKcOvYDy0OU?list=RDwKcOvYDy0OU" title="Paisaje" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


### Charly García

Charly García nació el 23 de octubre de 1951. Su música explora múltiples 
géneros desde: folk rock, rock progresivo, new wave, 
pop rock, pop barroco y synth pop. En su adolescencia fundó la banda [Sui
Generis](https://es.wikipedia.org/wiki/Sui_Generis_(banda)) junto a su compañero
de clase [Nito Mestre](https://es.wikipedia.org/wiki/Nito_Mestre).

<iframe width="658" height="370" src="https://www.youtube.com/embed/h9AHQV3pPn8?list=RDh9AHQV3pPn8" title="Charly García - Ojos De Video Tape (Audio)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Pacifica

Pacifica es un dúo femenino de indie rock/garage rock, formado por Inés Adam y
Martina Nintzel. Conocidas por hacer covers de [The Strokes](https://en.wikipedia.org/wiki/The_Strokes) aunque han lanzado un álbum con temas propios.

<iframe width="658" height="370" src="https://www.youtube.com/embed/9HqVMsYv05A?list=RDWKrt2JwUFYQ" title="Pacifica - Change Your Mind (Official Music Video)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Brasil

### Raul Seixas

Raul Seixas nació el 28 de junio de 1945. Cantor y compositor, pionero del **rock
brasileño**. Junto a algunos amigos, formo un grupo llamado "s Relâmpagos do
Rock" que no tuvo éxito. Luego, comenzó su carrera solista a principios de la
década de 1970.

<iframe width="658" height="468" src="https://www.youtube.com/embed/CmB4sfoZkwo?list=RDCmB4sfoZkwo" title="Metamorfose Ambulante" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Uruguay

### Ruben Rada

Empezó en la música cuando tenía diez años, como integrante de la comparsa de
negros y lubolos Morenada. De los quince a los dieciséis salió en una murga que
se llamaba "La Nueva Milonga". A los diecisiete debutó como *frontman* en la banda
"Los Hot Blowers" con el seudónimo Richie Silver. En 1969 logró grabar su primer
álbum como solista "Rada".

<iframe width="658" height="468" src="https://www.youtube.com/embed/K3tNbHU6Y78?list=RDK3tNbHU6Y78" title="No Me Queda Más Tiempo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


## Colombia

### Shakira

Apodada la Reina del pop latino, inició su carrera en 1991 y luego de unos
intentos fallidos, lanzó el álbum "Pies descalzos", que fue un éxito. Años
después, en 1998, lanzó "¿Dónde están los ladrones?" que fue otro éxito.

<iframe width="658" height="468" src="https://www.youtube.com/embed/fgvD663h9Os?list=RDfgvD663h9Os" title="Shakira - Inevitable (Audio)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Panama

### Billy Cobham

Nació el 16 de mayo de 1944. Su primera experiencia como batería en una banda fue en el ejército
estadounidense, donde adquirió cierta fama. Participó de bandas emblemáticas
como [Mahavishnu Orchestra](https://es.wikipedia.org/wiki/Mahavishnu_Orchestra).
En 1973 graba su primer álbum como solista "Spectrum" el cual abarca el género
de *jazz fusion*.

<iframe width="658" height="468" src="https://www.youtube.com/embed/RncVJZDHBKg?list=OLAK5uy_lc2PVEnoBfwwJZ4RsNnVwG7B3Hg21qOXc" title="A Light Shines In Your Eyes Summit Afrique (Excerpts From...)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Estados unidos

### Tom Petty and The Heartbreakers

Banda de rock formada en 1976, fundada por [Tom
Petty](https://es.wikipedia.org/wiki/Tom_Petty) en la cual estaban también:
[Mike Campbell](https://es.wikipedia.org/wiki/Mike_Campbell), [Ron
Blair](https://es.wikipedia.org/wiki/Ron_Blair), [Stan
Lynch](https://es.wikipedia.org/wiki/Stan_Lynch) y [Benmont
Tench](https://es.wikipedia.org/wiki/Benmont_Tench). Fue una de las principales
bandas del movimiento [heartland
rock](https://es.wikipedia.org/wiki/Heartland_rock) y tiene muchos éxitos, como
"Learning to Fly" o "Refugee".

<iframe width="658" height="370" src="https://www.youtube.com/embed/haRhA6AZpcU?list=RDhaRhA6AZpcU" title="Tom Petty  - You Wreck Me (Official Lyric Video)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Mazzy Star

Es una banda de rock alternativo formada en 1989 por [David
Roback](https://es.wikipedia.org/wiki/David_Roback) y Kendra Smith.
Posteriormente, Smith dejaría la banda, siendo reemplazada por [Hope
Sandoval](https://es.wikipedia.org/wiki/Hope_Sandoval) en el rol de vocalista. Se 
hicieron conocidos por el éxito "Fade into You" a mediados de los años 1990.
Sandoval escribía las letras y Roback componía la música.

<iframe width="658" height="468" src="https://www.youtube.com/embed/FGzNErpGZPg?list=RDFGzNErpGZPg" title="Blue Flower" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Francia

### Air

Es una banda de música electrónica formada en 1995, compuesta por: [Jean-Benoît
Dunckel](https://es.wikipedia.org/wiki/Jean-Beno%C3%AEt_Dunckel) y [Nicolas
Godin](https://es.wikipedia.org/wiki/Nicolas_Godin). Fueron altamente aclamados
por la crítica por su primer LP, llamado [Moon
Safari](https://es.wikipedia.org/wiki/Moon_Safari) en 1998.

<iframe width="658" height="468" src="https://www.youtube.com/embed/ZBVK7Z9AyNM?list=RDZBVK7Z9AyNM" title="Cherry Blossom Girl" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Reino Unido

### Morcheeba

Banda electrónica formada a mediados de 1990 por los hermanos Paul y Ross
Godfrey, quienes más tarde reclutaron a Skye Edwards como vocalista. Su último
álbum al día de la fecha salió en 2025, llamado "Escape the Chaos".

<iframe width="658" height="468" src="https://www.youtube.com/embed/2i03_L_tsY0?list=RD2i03_L_tsY0" title="Way Beyond" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

### Zero 7

Esta banda de *trip hop* está asociada con la corriente *downtempo*. Formada por
Henry Binns y Sam Hardaker, ambos amigos de la adolescencia. En 1999, lanzaron
su primer EP llamado EP1, del cual vendieron algunas copias. A mediados de 2001,
lanzaron "Simple Things", el cual relata en sus canciones hechos de la vida
cotidiana como pasear al perro.

<iframe width="658" height="370" src="https://www.youtube.com/embed/U_OKigBRqBI?list=RDU_OKigBRqBI" title="Zero 7 - Destiny (Official Video) ft. Sia, Sophie Barker" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


