---
title: Dos consejos para mejorar en ajedrez
author: Lucas Martino
date: '2026-02-15'
toc: true
slug: dos-consejos-para-mejorar-en-ajedrez
categories: []
tags: []
---

## Ajedrez

El **ajedrez** es un juego que no necesita presentación. Además, hoy en día existen
varias plataformas donde no solo podemos jugar, sino también aprender sobre las
**estrategias para dominar el juego**. Las más conocidas son:

- [Chess.com](www.chess.com)
- [Lichess.org](https://lichess.org)

Yo personalmente, prefiero jugar en [Lichess.org](https://lichess.org), ya que
es una plataforma completamente gratuita. Pueden seguirme entrando a [mi
perfil](https://lichess.org/@/lucasmartino), de esa manera podemos estar en
contacto dentro de la plataforma y **jugar partidas**.

## Consejos

### 1. Descansar luego de algunas partidas

Este concepto lo aprendí de otros juegos competitivos. Luego de jugar unas
cuantas partidas competitivas, es normal **sentir cansancio y jugar por
inercia**.

Esto puede llevarnos a cometer errores simples y perder muchas partidas. Por eso
recomiendo **tomarse unos minutos de descanso** luego de llevar unas cuantas
partidas. El número depende de cada jugador, yo diría que el cansancio se empiza
a sentir **luego de cinco partidas seguidas**.

### 2. Mirar cómo juegan los mejores

Hoy en día hay muchos creadores de contenidos que se dedican a comentar partidas
competitivas de ajedrez. Esto es muy útil ya que es una forma **muy pedagógica** de
ver en qué cosas podemos mejorar. Yo sigo esta cuenta: [Partidas Inmortales de
Ajedrez](https://www.youtube.com/c/PartidasInmortalesdeAjedrez).
